// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        return ios;
      default:
        return android;
    }
  }

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: Env.apiKeyAndroid,
    appId: '1:868341775085:android:2e5b1e1bdc309929fb6ae4',
    messagingSenderId: '868341775085',
    projectId: 'fruithub-84bf2',
    storageBucket: 'fruithub-84bf2.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: Env.apiKeyIos,
    appId: '1:868341775085:ios:061aed14ae4faeb0fb6ae4',
    messagingSenderId: '868341775085',
    projectId: 'fruithub-84bf2',
    storageBucket: 'fruithub-84bf2.firebasestorage.app',
    androidClientId:
        '868341775085-17m45j5cov1gug1s8dbrfejublldcngv.apps.googleusercontent.com',
    iosClientId:
        '868341775085-mqls2jn8aa0069lvd4ecr08urb4hp2d0.apps.googleusercontent.com',
    iosBundleId: 'com.fruithub.app',
  );
}
