name: Flutter CI/CD

on:
  push:
    branches:
      - main
      - cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.9'

      # 4. بينزل المكتبات
      - name: Install Dependencies
        run: flutter pub get

      # (جديد) 5. بيكريت ملف الـ .env وبياخد القيم من الـ GitHub Secrets
      - name: Create .env file
        run: |
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env
          echo "STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}" >> .env
          echo "PAYPAL_SECRET_KEY=${{ secrets.PAYPAL_SECRET_KEY }}" >> .env
          echo "PAYPAL_CLIENT_ID=${{ secrets.PAYPAL_CLIENT_ID }}" >> .env
          echo "API_KEY_IOS=${{ secrets.API_KEY_IOS }}" >> .env
          echo "API_KEY_ANDROID=${{ secrets.API_KEY_ANDROID }}" >> .env

      # (جديد) 6. بيشغل الـ build_runner عشان envied يولد ملف الـ env.dart
      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs

      # 7. بيعمل Run للـ Tests اللي إنت كاتبها
      - name: Run Tests
        run: flutter test

      # (جديد) تجهيز ملفات التوقيع (الختم) للأندرويد
      - name: Setup Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      # 8. بيعمل Build للـ APK
      - name: Build APK
        run: flutter build apk --release

      # 9. بيحتفظ بالـ APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk


        # 10. رفع الـ APK على Firebase App Distribution
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk